services:
  weather-source:
    image: python:3.11
    working_dir: /app
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - REDIS_HOST=redis
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./output:/app/output
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host

  redis:
    image: redis:latest
    ports:
      - "6380:6380"

  celery-worker:
    image: python:3.11
    working_dir: /app
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - REDIS_HOST=redis
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./output:/app/output
    command: sh -c "pip install -r requirements.txt && celery -A produce.celery worker --loglevel=info"
