version: "3.8"

services:
  weather-source:
    build: .
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - REDIS_HOST=redis
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./output:/app/output

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - REDIS_HOST=redis
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A produce.celery worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./output:/app/output
